# Generated by Django 6.0.5 on 2026-05-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_purchaseorder_purchaseorderline"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="invoice_number",
            field=models.CharField(
                blank=True,
                max_length=80,
                verbose_name="Factura o comprobante nro.",
            ),
        ),
    ]
