# Generated by Django 6.0.5 on 2026-05-25 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_purchaseorder_invoice_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('old_cost_price', models.PositiveIntegerField(verbose_name='Costo anterior')),
                ('new_cost_price', models.PositiveIntegerField(verbose_name='Costo nuevo')),
                ('old_sale_price', models.PositiveIntegerField(verbose_name='Precio anterior')),
                ('new_sale_price', models.PositiveIntegerField(verbose_name='Precio nuevo')),
                ('old_margin_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Margen anterior %')),
                ('new_margin_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Margen nuevo %')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_history_entries', to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='catalog.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Historial de precio',
                'verbose_name_plural': 'Historial de precios',
                'ordering': ['-changed_at', '-id'],
            },
        ),
    ]
