# Generated by Django 6.0.5 on 2026-05-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_customer_order_orderline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AddField(
            model_name='product',
            name='classification',
            field=models.CharField(choices=[('A', 'A / Signature'), ('B', 'B / Essentials'), ('C', 'C / Bijou')], default='B', max_length=1, verbose_name='Clasificación'),
        ),
    ]
