# Generated by Django 6.0.5 on 2026-05-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_product_product_type_product_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='care_instructions',
            field=models.TextField(blank=True, verbose_name='Cuidados'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=100, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='product',
            name='detailed_material',
            field=models.CharField(blank=True, max_length=300, verbose_name='Material detallado'),
        ),
        migrations.AddField(
            model_name='product',
            name='display_priority',
            field=models.PositiveIntegerField(default=0, verbose_name='Prioridad web'),
        ),
        migrations.AddField(
            model_name='product',
            name='finish',
            field=models.CharField(blank=True, max_length=100, verbose_name='Acabado'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Destacado'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_hypoallergenic',
            field=models.BooleanField(default=False, verbose_name='Hipoalergénico'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_water_resistant',
            field=models.BooleanField(default=False, verbose_name='Resistente al agua'),
        ),
        migrations.AddField(
            model_name='product',
            name='measurements',
            field=models.CharField(blank=True, max_length=200, verbose_name='Medidas'),
        ),
        migrations.AddField(
            model_name='product',
            name='public_tags',
            field=models.CharField(blank=True, max_length=300, verbose_name='Tags públicos'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Descripción SEO'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, max_length=300, verbose_name='Título SEO'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Descripción corta'),
        ),
        migrations.AddField(
            model_name='product',
            name='visible_on_web',
            field=models.BooleanField(default=False, verbose_name='Visible en web'),
        ),
    ]
