# Generated by Django 6.0.5 on 2026-05-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0010_product_care_instructions_product_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_city",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Ciudad de entrega"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_type",
            field=models.CharField(
                choices=[("pickup", "Retiro en Asunción"), ("shipping", "Envío")],
                default="pickup",
                max_length=20,
                verbose_name="Modalidad de entrega",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Descuento (Gs.)"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cash", "Efectivo"),
                    ("transfer", "Transferencia"),
                    ("ueno", "Ueno"),
                    ("other", "Otro"),
                ],
                default="",
                max_length=20,
                verbose_name="Método de pago",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("whatsapp", "WhatsApp"),
                    ("instagram", "Instagram"),
                    ("facebook", "Facebook"),
                    ("referral", "Referido"),
                    ("other", "Otro"),
                ],
                default="",
                max_length=20,
                verbose_name="Canal de origen",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Borrador"),
                    ("confirmed", "Confirmado"),
                    ("deposit", "Seña recibida"),
                    ("delivered", "Entregado"),
                    ("cancelled", "Cancelado"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
    ]
