# Generated by Django 6.0.5 on 2026-05-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0011_order_delivery_city_order_delivery_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="ruc",
            field=models.CharField(blank=True, max_length=30, verbose_name="RUC"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Borrador"),
                    ("confirmed", "Confirmado"),
                    ("deposit", "Seña recibida"),
                    ("invoice_pending", "Factura pendiente"),
                    ("delivered", "Entregado"),
                    ("cancelled", "Cancelado"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
    ]
