# Generated by Django 6.0.5 on 2026-05-26 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0012_customer_ruc_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderline",
            name="stock_reserved_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="catalog.product",
                verbose_name="Producto reservado en stock",
            ),
        ),
        migrations.AddField(
            model_name="orderline",
            name="stock_reserved_quantity",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Cantidad reservada en stock"
            ),
        ),
    ]
